cpe_mapping = {
    "cpe:/o:microsoft:windows_server_2016:-": "Windows Server 2016",
    "cpe:/o:microsoft:windows_server_2012:r2": "Windows Server 2012 R2",
    "cpe:/o:microsoft:windows_10:21h2::x64": "Windows 10 21H2 (x64)",
    "cpe:/a:microsoft:edge:chromium-based": "Microsoft Edge Chromium-based",
    "cpe:/o:microsoft:windows_server_2019": "Windows Server 2019",
    "cpe:/o:microsoft:windows_10": "Windows 10",
    "cpe:/o:astra_linux:astra_linux_se:1.5": "Astra Linux SE 1.5",
    "cpe:/o:astra_linux:astra_linux_se:1.6": "Astra Linux SE 1.6",
    "cpe:/o:astra_linux:astra_linux_se:1.7": "Astra Linux SE 1.7",
    "cpe:/o:alt:alt_8_sp": "ALT Linux 8 SP",
    "cpe:/o:microsoft:windows_10:22h2::x64": "Windows 10 22H2 (x64)",
    "cpe:/a:microsoft:sql_server:2014:sp1": "Microsoft SQL Server 2014 SP1",
    "cpe:/a:microsoft:windows_defender": "Microsoft Windows Defender",
    "cpe:/o:unix": "Unix",
    "cpe:/a:openssl:openssl": "OpenSSL",
    "cpe:/o:microsoft:windows": "Microsoft Windows",
    "cpe:/a:google:chrome:admin_install_for_all_users": "Google Chrome Admin Install for All Users",
    "cpe:/a:mozilla:firefox": "Mozilla Firefox",
    "cpe:/o:microsoft:windows_10:::x64": "Windows 10 (x64)",
    "cpe:/a:erlang-otp:erlang-otp": "Erlang OTP",
    "cpe:/a:microsoft:.net_core": ".NET Core",
    "cpe:/a:microsoft:.net_framework:3.5": ".NET Framework 3.5",
    "cpe:/a:microsoft:.net_framework:4.7.1": ".NET Framework 4.7.1",
    "cpe:/a:microsoft:.net_framework:4.7.2": ".NET Framework 4.7.2",
    "cpe:/a:adobe:shockwave_flash_activex": "Adobe Shockwave Flash ActiveX",
    "cpe:/a:adobe:acrobat_reader:11": "Adobe Acrobat Reader 11",
    "cpe:/a:microsoft:.net_framework:4.7": ".NET Framework 4.7",
    "cpe:/a:wireshark:wireshark": "Wireshark",
    "cpe:/a:google:chrome": "Google Chrome",
    "cpe:/a:microsoft:.net_framework:4.6.2": ".NET Framework 4.6.2",
    "cpe:/a:don_ho:notepad++": "Notepad++",
    "cpe:/a:7-zip:7-zip": "7-Zip",
    "cpe:/a:apache:http_server": "Apache HTTP Server",
    "cpe:/a:microsoft:sql_server:2012": "Microsoft SQL Server 2012",
    "cpe:/a:pgadmin:pgadmin:admin_install_for_all_users": "PGAdmin Admin Install for All Users",
    "cpe:/a:simon_tatham:putty": "PuTTY",
    "cpe:/a:microsoft:malicious_software_removal_tool": "Microsoft Malicious Software Removal Tool",
    "cpe:/a:winscp:winscp": "WinSCP",
    "cpe:/a:graphviz:graphviz": "Graphviz",
    "cpe:/a:microsoft:visual_c++:2005:redistribution_pkg": "Microsoft Visual C++ 2005 Redistribution Package",
    "cpe:/a:nmap": "Nmap",
    "cpe:/a:microsoft:3d_viewer": "Microsoft 3D Viewer",
    "cpe:/a:microsoft:asp.net_core": "ASP.NET Core",
    "cpe:/a:microsoft:edge": "Microsoft Edge",
    "cpe:/a:microsoft:heif_image_extensions": "Microsoft HEIF Image Extensions",
    "cpe:/a:microsoft:ie:11": "Internet Explorer 11",
    "cpe:/a:microsoft:microsoft_photos": "Microsoft Photos",
    "cpe:/a:microsoft:office_app": "Microsoft Office App",
    "cpe:/a:microsoft:paint_3d": "Microsoft Paint 3D",
    "cpe:/a:microsoft:screen_sketch": "Microsoft Screen Sketch",
    "cpe:/a:microsoft:visual_studio:2010": "Microsoft Visual Studio 2010",
    "cpe:/a:microsoft:vp9_video_extensions": "Microsoft VP9 Video Extensions",
    "cpe:/a:microsoft:web_media_video_extensions": "Microsoft Web Media Video Extensions",
    "cpe:/a:oracle:jre": "Oracle Java Runtime Environment",
    "cpe:/a:oracle:jre:1.8.0": "Oracle Java Runtime Environment 1.8.0",
    "cpe:/a:oracle:vm_virtualbox:7.0": "Oracle VM VirtualBox 7.0",
    "cpe:/a:pivotal_software:rabbitmq_server": "RabbitMQ Server",
    "cpe:/a:postgrespro:postgrespro:nix": "PostgresPro for Unix",
    "cpe:/a:libreoffice:libreoffice": "LibreOffice",
    "cpe:/a:postgresql:postgresql": "PostgreSQL",
    "cpe:/a:saltstack:salt": "SaltStack",
    "cpe:/a:microsoft:.net_framework:4.8": ".NET Framework 4.8",
    "cpe:/a:altex-soft:redcheck": "RedCheck",
    "cpe:/a:altex-soft:redcheckagent": "RedCheckAgent",
    "cpe:/a:vmware:tools": "VMware Tools",
}
